[WIP] Integrates google scholar's citation count functionality
JabRef/JabRef-Browser-Extension pull request #131
Opened 2020-02-06 13:35 UTC by systemoperator

work in progress...

2020-02-06 15:38 UTC, systemoperator commented
I am looking for a very easy way to wait until all (asynchronously) fetched citation counts have been received in the method `zsc.processItems()` in file `zsc_misc_post.js`. Suggestions are welcome.

2020-02-06 23:55 UTC, systemoperator commented
Fetching and transferring citation counts to JabRef works now. :) Currently, the citation data is not fetched asynchronously (which probably has the benefit, that it might reduce the amount of required captchas of Google Scholar to show that one is not a robot).

2020-02-07 16:27 UTC, tobiasdiez commented
Thanks a lot for your PR. I really like the feature and think it's a valuable addition to the JabRef eco system. However, I'm not convinced that this should be backed into the browser extension. Instead I would prefer if it would be directly implemented in JabRef. Feels like the more flexible approach that also covers other use cases (e.g. articles added by hand instead of via the browser). But I guess you have thought about this also. Why did you choose to implement it as an addition to the browser extension?

2020-02-08 09:58 UTC, systemoperator commented
@tobiasdiez 

My main reasoning was as follows:

1. Most important aspect: browsers simply work for Google Scholar
Fetching Google Scholar data from real browsers simply works. When fetching it from somewhere else, it does not or hardly does. Apparently Google does quite a good job for guaranteeing that. JabRef already offers searching articles from Google Scholar, but it is simply hardly usable, because it does not work most of the time. Honestly, I already played with the idea to also migrate the existing JabRef functionality "Web Search" using Google Scholar to the JabRef-Browser-Extension (meaning, letting the browser extension query the information from Google Scholar and then returning it to JabRef), because then it would be much more reliable. Google Scholar has integrated measures to prevent automated queries. To make sure robots are not involed, e.g. captchas are used. The captchas need to be solved manually so that queries will succeed. So user interaction is needed. In my experiece correctly solved captchas are somehow linked to the browser, where they got solved, which is apparently another quite relevant issue. When one had been solved correctly, then quite a lot queries are possible, at least, if they are not too much or too frequent. The implementation within the JabRef-Browser-Extension guarantees all functional requirements, because even if solving a captcha is required, the user gets an alert, can solve it and then this browser is (re-)enabled and possible to fetch the required information.

2. Reusing code
Most of the current impementation has been used within another web extension, which showed really reliable results. The implementation process was easier, faster and updates of the existing extension can be directly merged into the JabRef-Browser-Extension, if wanted.

I have also thought about the use case where citation counts of references within JabRef should be fetched or updated (see: https://github.com/JabRef/jabref/issues/5849), which covers references imported from the browser extension and e.g. manually imported ones. Actually, I see this use case (tiggering fetching citation counts from JabRef) as the primary one. For this case my idea was sending a request (with either one or several references) from JabRef to the JabRef-Browser-Extension, which subsequently fetches the required data and then sends the required information back to JabRef. If the user is required to solve a captcha, the user could be notified within JabRef. Probably also opening a corresponding browser tab and loading an url could be possible/sensible.

The formal steps in JabRef would be:
1. Select elements in JabRef library, where the citations counts should be fetched/updated (Or probabily: if no entries are selected: fetch for whole library)
2. Trigger fetching/updating process

Even if a headless webbrowser was used within JabRef, there would still be the problem/challenge with solving Google Scholar's "not-a-robot" checks. Maybe it is possible to permanently "hold" a browser instance for retrieving data from Google Scholar within JabRef and to show a browser window whenever some user interaction for solving a captcha is required, where the user solves it and hopefully Google Scholar will probably accept it. But..., from a bird's eye perspective, this is actually already quite similar to the current approach, right? So I thought, the existing JabReb-Browser-Extension is a good starting point to integrate this. Probably, special cases need special treatment. The cool thing with browser extensions is, that they are really customizable.

I know, the current design is probably a somewhat clumsy approach, but at least it works really good and in the end guaranteeing functionality has highest priority. In my opinion, for now this was at least the easiest way to go.

2020-02-10 11:31 UTC, systemoperator commented
What do you think is the proper roadmap for this situation?

2020-02-10 12:23 UTC, tobiasdiez commented
That are some really good points that you brought up. Let me think about it for a bit... I'm pretty busy at the moment, sorry. I'll get back to you soon, promised!

2020-02-13 23:03 UTC, systemoperator commented
Maybe relevant for decision process:
- https://github.com/JabRef/jabref/issues/4423
- https://github.com/JabRef/jabref/issues/4027
- WebDrivers like selenium are sometimes reported getting identified as automated web scraping processes, thus more and more effort is necessary to prevent this.

2020-02-15 10:05 UTC, tobiasdiez commented
So finally found some time to think about these matters. Thanks again for the detailed outline above which was good food for thought. 

There are a few things of concern:
1. The communication in the direction JabRef > JabFox in the browser is not possible. (To be more precise, only JabFox can send requests to JabRef and wait for responses. So in principle you could let JabFox constantly poll JabRef and asks if there is something to process and then send back the result. But given all the problems we already have or had making the simple "JabFox to JabRef" communication work, this will be a lot of work and I would be surprised if it results in a stable solution.). Thus it is not possible to update citation counts from JabRef by using JabFox.
2. Fetching data from google is prone to run into quota problems and google will block further requests and ask for captcha input. This happens a lot currently using the web fetcher as is apparent from huge amount of issues on these matters. We tried to speak with google about this and establish a proper api or another solution, but this lead nowhere so far. Thus, I agree, using the citation fetch functionality in JabRef will run into similar problems.

Thus, it appears that there is now good way to fetch citations counts from google. Either using JabFox or JabRef leads to nasty issues. 

Proposal: Don't use google. There are a few services that provide citation meta data using a freely available api. For example, [Microsoft Academic API](https://docs.microsoft.com/en-us/azure/cognitive-services/academic-knowledge/calchistogrammethod) or [opencitations](https://opencitations.net/) or [semantic scholar](http://api.semanticscholar.org/). Personally I would tend to use semantic scholar as the seem to have the most extensive data coverage. These api can be simply consumed directly from JabRef.

The advantages of this approach are multiple: you have a stable api to consume, which makes it a reliable and future proof solution, you get more metadata than just the citation count (e.g. it could be extended in the future to actually show a list of citing works providing easy ways to import them etc) and you don't need to worry about cross-communication JabRef <-> JabFox.   

What do you think?

2020-02-15 13:55 UTC, systemoperator commented
For now, I cannot respond in detail. I need to inspect the APIs in detail as well. Just some fragments to think about:
- From an API it would be good to query references with the same criteria like in Google Scholar (title, authors, year), since not for every reference a DOI or something else is provided. (Furthermore there are many differente identifiers, which could be a problem as well.)
- It is important to consider how complete other databases are in terms of actually finding entries.

Google Scholar
- I have created a small project and made some tests with selenium. Basically it works better than expected at the beginning. But at some point lots of capchas appear, which need to be solved. But this depends on how intense the service is used.
- Just an idea: What if we start a small websocket server in JabRef and a websocket endpoint in JabFox for a fast, local (localhost), bidirectional connection?

2020-02-16 10:46 UTC, systemoperator commented
I am in the process of adding a general structure for fetching reference metadata, which will allow fetching manifold metadata. For now I will add the semantic scholar for fetching citation counts, since it is very easy. Furthermore I am also in the process of adding a small websocket server in JabRef for bidirectional communication between JabRef and JabFox, which will be much more stable. It will now be used for fetching the citation counts from Google Scholar as well. (Since it has the most accurate and most complete information. Semantic Scholar e.g. states for a reference 3 citation counts but Google Scholar states 33. Furthermore semantic scholar requires some identifier like DOI, but not every reference has one. I am confident, that this approach will work acceptable fine, if used properly and moderately. Additionally Google Scholar finds entries where others don't.) This websocket connection can later be used for other communication purposes as well.

2020-02-18 12:00 UTC, tobiasdiez commented
Sounds really nice! Thanks for your work @systemoperator. 

I agree that the data of semantic scholar is not yet on the same level as google scholar, but I hope they are getting there. As you said, they have a nice API.

Web sockets. The last time I looked at them, it was not possible to communicate from a browser extension via sockets (i.e. the web sockets API is not accessible). According to https://bugzilla.mozilla.org/show_bug.cgi?id=1247628 this is still the case. If I remember correctly for chrome it might work but you need additional permissions. If you find a solution, that would be nice. This would make it possible to make progress on https://github.com/JabRef/JabRef-Browser-Extension/issues/32 and https://github.com/JabRef/jabref/issues/5719

2020-02-18 20:16 UTC, systemoperator commented
Currently, I start the websocket client as a background script. I have made some tests with it and it seems to meet all my requirements. At least, I could already send some test websocket messages to JabRef and receive some as well. :) I hope I will not find any pitfalls and I hope this meets all future requirements as well.

2020-02-20 17:56 UTC, systemoperator commented
I don't understand, how this code fragment creates the bibtex data:
https://github.com/JabRef/JabRef-Browser-Extension/blob/7072f376f7a0dd78747d977eedee51a81bc1c907/connector.js#L49-L68
Where and how does the conversion process take place?

2020-02-20 22:04 UTC, tobiasdiez commented
It's a bit of a ping pong play as some code has to be invoked in the "background" (i.e. in the extension context), some in the "foreground" (e.g. the update of the popup dialog) and some needs to be embedded in the current tab (to access was is displayed). 

Here, the above code triggers 
https://github.com/JabRef/JabRef-Browser-Extension/blob/091ed6b6a9215364cee4e2447093757c7d575511/bibtexConverter.js#L47-L48
which then invokes
https://github.com/JabRef/JabRef-Browser-Extension/blob/091ed6b6a9215364cee4e2447093757c7d575511/bibtexConverter.js#L1-L17
which transforms the item to bibtex.

2020-02-22 23:49 UTC, tobiasdiez commented
I scrolled through the code and it already looks very good. Thanks for your work!

Just to make sure that we don't run into unhappy surprises later, can you please check that the websockets in the bundled extension still works when you install it manually (and not using web-ext run) as described here: https://extensionworkshop.com/documentation/develop/test-permission-requests/

2020-02-23 10:21 UTC, systemoperator commented
That's a good point! I have tested it and it works. :) When installing it, the following gets stated:

It requires your permission to:
- Access your data for all websites
- Exchange messages with programs other than Firefox
- Access browser tabs
- Accesss browser activity during navigation

2020-02-23 10:32 UTC, tobiasdiez commented
Very nice!

2020-02-26 15:06 UTC, systemoperator commented
From my side, everything is complete. :)

2020-03-13 12:27 UTC, tobiasdiez commented on connector.js
> +					globalSettings.exportMode = configuration.exportMode || 2;
Is it really necessary to have `globalSettings`? I would prefer if the relevant preferences are just passed around as additional data (or retrieved anew using `browser.storage`)

2020-03-13 12:27 UTC, tobiasdiez commented on bibtexConverter.js
> +		console.log("using BibLaTeX converter...");
Please combine this with log statement with the one above (otherwise it's getting to verbose)

2020-03-13 12:28 UTC, tobiasdiez commented on connector.js
> +					console.log("exportMode: " + globalSettings.exportMode);
please use `console.debug` here

2020-03-13 12:29 UTC, tobiasdiez commented on connector.js
> +							data.items[i] = new ZscItem(data.items[i]);
Does it also work to create a new array containing the `ZscItems` instead of overriding `data.items`?

2020-03-13 12:31 UTC, tobiasdiez commented on data/options.html
> +            <label>WS Connection Status</label>
Please don't abbreviate `Websocket` here

2020-03-13 12:32 UTC, tobiasdiez commented on data/options.html
> +            <span id="wsClientStatus">pending...</span>
Just an idea: can we merge the status codes to one corresponding to the complete websocket connection? (I.e. first check if the websocket client work, and then the connection to JabRef)

2020-03-13 12:35 UTC, tobiasdiez commented on data/progressPanel.js
> +		setTimeout(function() { window.close(); }, 3000);
Why did you change this?

2020-03-13 12:35 UTC, tobiasdiez commented on data/progressPanel.js
> +		//document.getElementById("googleScholarCaptchaLink").innerHTML = message.onGoogleScholarCaptcha;
Please remove the commented-out code

2020-03-13 12:40 UTC, tobiasdiez commented on gulpfile.js
> +		'./zsc/**/*'
Can you combine the `process-zsc-scripts` with the `process-zotero-scripts` by adding the `zsc` folder to the `sources` variable above.

2020-03-13 12:41 UTC, tobiasdiez commented on gulpfile.js
> +gulp.task('update-zsc-scripts', gulp.series('copy-zsc-scripts', 'process-zsc-scripts'));
I would add `copy-zsc-scripts` to the `update-zotero-scripts` task (and mabye rename the later to `update-external-scripts`.

2020-03-13 12:42 UTC, tobiasdiez commented on jabref-browser-extension.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Is this file needed?

2020-03-13 12:43 UTC, tobiasdiez commented on package.json
> +  "version": "1.0.0",
The version is not correct. Is this really required? 

`keywords ` and `author` also shouldn't be empty I guess

2020-03-13 12:55 UTC, tobiasdiez commented on zsc_misc_post.js
> +zsc.processItems = function(items) {
For the `zotero` scripts, I use the following strategy that works quite well. Include the original scripts as git subtree and *make changes directly to corresponding files*. This makes it easy to include upstream updates easily using a git merge. 

As it seems that some methods of the `pre` and `post` scripts are copied versions, I would prefer if you could employ a similar strategy here as well instead of overwriting the complete method.

2020-03-13 17:35 UTC, systemoperator commented on data/options.html
> +            <label>WS Connection Status</label>
Initially, I had "Websocket Connection Status", but then it was too long and a line break occured, which looked quite ugly, so I changed it.

2020-03-13 17:43 UTC, systemoperator commented on data/progressPanel.js
> +		setTimeout(function() { window.close(); }, 3000);
I changed this, because otherwise with Firefox it occured quite often, that the content of message box could not be read, since it disappeard very fast. I added additional text into this message box which I wanted to read, but I was unable to since occasionally the relevant text updates were only visible for some milliseconds, as the message box closed.

2020-03-13 19:39 UTC, systemoperator commented on .idea/.gitignore
> +# Default ignored files
> [... ] I guess for the websocket communication, also changes in JabRef are necessary, right?

Yes, there is a PR: https://github.com/JabRef/jabref/pull/5943

2020-03-13 19:40 UTC, systemoperator commented
> [...] I guess for the websocket communication, also changes in JabRef are necessary, right?

Yes, there is a PR: https://github.com/JabRef/jabref/pull/5943

2020-03-13 20:20 UTC, systemoperator commented on connector.js
> +					globalSettings.exportMode = configuration.exportMode || 2;
It is not necessary, I just thought of some applications, where it could be handy to access it somewhere else easily. Accessing it asynchronously can be difficult in some situations. For now it could be removed, but I thought of future applications.

2020-03-13 20:37 UTC, systemoperator commented on bibtexConverter.js
> +		console.log("using BibLaTeX converter...");
done

2020-03-13 20:43 UTC, tobiasdiez commented on data/options.html
> +            <label>WS Connection Status</label>
Maybe only `Websocket status`?

2020-03-13 20:45 UTC, systemoperator commented on data/options.html
> +            <label>WS Connection Status</label>
Good compromise!

2020-03-13 20:46 UTC, tobiasdiez commented on connector.js
> +					globalSettings.exportMode = configuration.exportMode || 2;
You can always use `await` to get a synchronous call. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

2020-03-13 20:52 UTC, systemoperator commented on connector.js
> +					globalSettings.exportMode = configuration.exportMode || 2;
Cool, I will test it. If it works, then I can simplify things and remove the global declaration. :)

2020-03-13 20:54 UTC, systemoperator commented on zsc_misc_post.js
> +zsc.processItems = function(items) {
I don't have experience with git subtrees. I need to look into that matter. :thinking:

2020-03-13 21:01 UTC, systemoperator commented on .idea/.gitignore
> +# Default ignored files
Concerning the `.idea` files, I was thinking a bit before adding them. Finally, I came to the conclusion that it could make sense to add them, since they contain project specifc settings (but not user specific settings) comparable to the settings in JabRef, which could still grow (e.g. checkstyle, ...). Nevertheless, I could again remove them, if these arguments are not that relevant.

2020-03-13 21:03 UTC, systemoperator commented on jabref-browser-extension.iml
> +<?xml version="1.0" encoding="UTF-8"?>
This file has been generated automatically when creating the project, thus it should not be needed.

2020-03-13 21:08 UTC, systemoperator commented on package.json
> +  "version": "1.0.0",
This file has been extended automatically when creating the project. Could this be a new convention which should be followed? Where is the current version number stored? I could set `author` to "JabRef-Browser-Extension developers" and add some keywords?

2020-03-13 21:22 UTC, systemoperator commented on connector.js
> +					globalSettings.exportMode = configuration.exportMode || 2;
Ok, but I think it only works with a async wrapper function, because the 'await' operator can only be used in an 'async' function: 

```javascript
async function f1() {
  var x = await resolveAfter2Seconds(10);
  console.log(x);
}
```

2020-03-13 21:47 UTC, tobiasdiez commented on zsc_misc_post.js
> +zsc.processItems = function(items) {
There is not a lot you need to know. You already have the files in the cloned folder `zotero-scholar-citations` folder. So just edit the files there directly (maybe adding a short comment why the changes are necessary - this makes merging upstream changes in the future easier).

2020-03-13 21:48 UTC, tobiasdiez commented on package.json
> +  "version": "1.0.0",
ok!
I think `author = JabRef` is fine and it would be nice if you could add a few keywords indeed. The version should only be specified in the manifest file, so please delete this line.

2020-03-13 21:48 UTC, tobiasdiez commented on jabref-browser-extension.iml
> +<?xml version="1.0" encoding="UTF-8"?>
In this case, please remove it and add it to gitignore

2020-03-13 23:19 UTC, systemoperator commented on connector.js
> +					globalSettings.exportMode = configuration.exportMode || 2;
Hm, I have tried

```javascript
let browserStorage = {
    get: async function(keys) {
        let result = await browser.storage.sync.get(keys)
            .catch((err) => { console.error(err); });
        return result;
    }
};
```

with

````javascript
let settings = browserStorage.get(['exportMode', 'takeSnapshots', 'retrieveCitationCounts']);
````

But it still does not work, due to https://stackoverflow.com/questions/49938266/how-to-return-values-from-async-functions-using-async-await-from-function.

I don't want to use something similar to 

````javascript
(async () => {
  console.log(await getData())
})()
````

as suggested in the link, as the script again does not wait at this point.

Now I can remember, that I have played around with this `await` a month ago concering this issue, but I did not find a satisfying solution...

2020-03-13 23:24 UTC, tobiasdiez commented on connector.js
> +					globalSettings.exportMode = configuration.exportMode || 2;
It's a bit strange but I would advice not to spend more time on it right now. It's not that important. 

Anyway, please remove the global settings object as it is not required right now and we can re-add in case it is really needed later. Thanks

2020-03-13 23:33 UTC, tobiasdiez commented on .idea/.gitignore
> +# Default ignored files
That's a good point. So I would follow https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems and use the gitignore from http://www.gitignore.io/api/intellij,sublimetext.

2020-03-14 20:49 UTC, systemoperator commented on gulpfile.js
> +gulp.task('update-zsc-scripts', gulp.series('copy-zsc-scripts', 'process-zsc-scripts'));
Would it be ok, to rename the folder `Zotero` (where all the files get collected) to e.g. `external-scripts`?

2020-03-14 21:02 UTC, tobiasdiez commented on gulpfile.js
> +gulp.task('update-zsc-scripts', gulp.series('copy-zsc-scripts', 'process-zsc-scripts'));
Yes that is fine with me

2020-03-14 22:19 UTC, systemoperator commented on gulpfile.js
> +gulp.task('update-zsc-scripts', gulp.series('copy-zsc-scripts', 'process-zsc-scripts'));
The current commit works, but just to be sure, that no other sources are affected by renaming the folder `Zotero` to `external-scripts`: The paths desclared in e.g. `./external-scripts/background.js` do not depend on the the folder `external-files`, right?

https://github.com/systemoperator/JabRef-Browser-Extension/blob/c0f0f14adb1a62d721ada74dd815ac561782ee35/external-scripts/background.js#L30-L54

2020-03-15 01:02 UTC, systemoperator commented on zsc_misc_post.js
> +zsc.processItems = function(items) {
done

2020-03-15 01:10 UTC, systemoperator commented
done

2020-05-13 10:42 UTC, systemoperator commented
The PR can be merged now and the ws client is disabled until the JabRef's counterpart has been integrated. :)

2021-01-20 20:42 UTC, tobiasdiez requested changes
Sorry for taking so long to come back to you.

I finally found the time to go through your PR again. I only have two small remarks concerning the code. Could you please take care of these, and fix the merge conflicts then I will merge and release a new version. Thanks!

2021-01-20 20:42 UTC, tobiasdiez commented on bibtexConverter.js
> +	if (conversionMode === 1) {
Please use `bibtex` and `biblatex` for the possible values of conversion mode.

2021-01-20 20:42 UTC, tobiasdiez commented on connector.js
> +					configuration.exportMode = configuration.exportMode || 2;
You can add default values as follows:
```
let gettingItem = browser.storage.local.get({
  kitten: "no kitten",
  monster: "no monster",
  grapefruit: {
    name: "Grape Fruit",
    eats: "Water"
  }
});
```

2021-01-20 20:42 UTC, tobiasdiez commented on data/options.js
> +			let takeSnapshots = res.takeSnapshots || false;
See above for how to handle default values.

2021-01-21 10:01 UTC, systemoperator commented
done :)

2021-01-21 12:41 UTC, tobiasdiez commented on package.json
> +		"yargs": "^16.2.0",
package-lock.json is intended to be checked into source control, can you please restore it. Thanks!

2021-01-21 13:04 UTC, systemoperator commented on package.json
> +		"yargs": "^16.2.0",
`package-lock.json` is still under version control, but its content is updated automatically. Shall I restore the original version of it which I have pulled initially?

2021-01-21 13:14 UTC, systemoperator commented on package.json
> +		"yargs": "^16.2.0",
I have reverted it to its original version.

2021-01-30 10:53 UTC, merged

2021-01-30 10:53 UTC, tobiasdiez commented
Many thanks again!